<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllData() {
        return $this->createQueryBuilder('v')
            ->select('v.id, v.file, u.username, u.email')
            ->leftJoin("v.user", "u")
            ->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY) ;
    }
}
